server:
  port: 9001
spring:
  application:
    name: consumer-movie
logging:
  level:
    root: INFO
    com.feng: DEBUG
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka7001:7001/eureka/,http://eureka7002:7002/eureka/
    fetch-registry: true
  instance:
    instance-id: consumer-movie9001

hystrix:
  command:
    default:
      circuitBreaker:
        requestVolumeThreshold: 50