
spring:
  application:
    name: eurekaServer7002
  profiles: e7002
server:
  port: 7002


eureka:
  server:
    enable-self-preservation: false
  instance:
    hostname: eureka7002
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka7001:7001/eureka/

