server:
  port: 6001
  servlet:
    context-path: /route
spring:
  application:
    name: simple-zuul

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka7001:7001/eureka/,http://eureka7002:7002/eureka/
    register-with-eureka: true
  instance:
    instance-id: zuul6001
zuul:
  routes:
#    myMovie:  # 自定义规则的名字，随便起
#      path: /myMovie/**
#      serviceId: PROVIDER-USER

  #简洁写法
    provider-user: /myUser/**
    consumer-movie: /myMovie/**

