server:
  port: 6001
spring:
  application:
    name: zuul

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka7001:7001/eureka/,http://eureka7002:7002/eureka/
    fetch-registry: true
  instance:
    instance-id: zuul6001
zuul:
  routes:
    myMovie:  #定义的规则名，可以随便起
      path: /zuulMovie/**
      serviceId: consumer-movie
